# app/db/models.py

from enum import Enum

class TranslationStatus(str, Enum):
    """Enum for the possible statuses of a concept."""
    ACTIVE = "active"           # Concept is active and its terms can be fetched
    INACTIVE = "inactive"       # Concept is inactive (e.g., low score)
    UNDER_REVIEW = "under_review" # Concept might need manual review

class ConceptGenerationMethod(str, Enum):
    """Enum for how a concept was initially generated."""
    LLM = "llm"                     # Generated by LLM without specific file context
    PLACEHOLDER_CONTEXT = "placeholder_context" # Generated by LLM using a context file
    MANUAL = "manual"               # Concept was created manually via API